title: "Kuan-Yu Wey's Personal Website (Testing)"
author: "Kuan-Yu (Wesley) Wey"
description: "University of California - Los Angeles"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

# show_social: true               # show title description and social links in the footer 
show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "CV_Kuan-Yu-2025.pdf", title: "CV"}
  - {title: "QMDS Lab", url: "https://sites.google.com/g.ucla.edu/quantum/"}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:wesleywey0717@g.ucla.edu"}
  - {title: Github, icon: github, url: "https://kywey.github.io"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
