title: "Kuan-Yu (Wesley) Wey"
author: "Kuan-Yu (Wesley) Wey"
description: "Physics PhD candidate · University of California, Los Angeles"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

# show_social: true               # show title description and social links in the footer 
show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter
show_social: true  


# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {title: "About Me", url: "/about/", sidebaricon: address-card}
  - {title: "Research", url: "/research/", sidebaricon: atom}
  - {title: "Fun Life", url: "/fun/", sidebaricon: flask}
  - {title: "CV", url: "/cv/", sidebaricon: file}
  - {title: "QMDS Lab", url: "https://sites.google.com/g.ucla.edu/quantum/", sidebaricon: university}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:wesleywey0717@g.ucla.edu"}
  - {title: Github, icon: github, url: "https://github.com/KYWey"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/kuan-yu-wey-7062b6305/"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed

# Collections
collections:
  physics:
    output: true
    permalink: /fun/physics/:name/
  lab:
    output: true
    permalink: /research/lab/:name/

defaults:
  - scope:
      path: ""
      type: physics
    values:
      layout: physics
      mathjax: true
  - scope:
      path: ""
      type: lab
    values:
      layout: lab
      mathjax: true
